### ISSUE TITLE
Explore if we should replace our openmpi and boost with homebrew on jenkins

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#105]
According to Andrey:

Cloudbees mac os machines have homebrew built in ( https://developer.cloudbees.com/bin/view/Mobile/Mac+OS+in+the+Cloud+-+Machine+Specifications+ ). Most of the alpscore dependencies (like boost or mpi) come precompiled (so called bottles - available by now for most of the packages). We could make use of that to install dependencies for our builds, instead of compiling them ourselves. This would probably make them slower, but would solve a problem with, for example, openmpi not being accessible on a filesystem.

We could also use that to
1) Create a precompiled alpscore package (see https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md ).
2) Create some of the precompiled dependencies with special flags.
3) Have more flexibility - check compatibility with different versions of packages by using https://github.com/Homebrew/homebrew-versions

**Comment by egull** [comment]
Andrey will take over - there are bugs in the homebrew script but brew exists on the machine.

**Comment by aeantipov** [comment]
Ok, so the jenkins/homebrew builds now and compiles and run tests. 
The xml files are unfortunately unavailable in this build right now, as homebrew cleans the build directory after successful build. There are several options:
- Leave it as it is in the binary state (works/not). This mimics the standard user experience.
- Make one more build (or not make the previous one), that instead of running `brew install alpscore` runs `brew unpack -pg alpscore`, which fetches the alpscore as a git repo and preinstalls the dependencies. After that a build.jenkins.sh with some changes can take over and we can have all the test output. 

##### Testing 
There is a homebrew test bot and a provided command `brew test alpscore` that checks the integrity of the package for homebrew. Normally this works best for the executables, as they are just run with some test parameters. For libraries, one normally provides a small source file that links to all dependent libraries (see `do test` section in https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb as an example). As far as I understand it's not meant to check a lot of tests. We could provide here our tutorials and link with them after we have #119 .

**Comment by aeantipov** [comment]
Actually `brew test boost` fails, so it's a bad example.
