### ISSUE TITLE
ALPS installs cmake files in wrong directory

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#113]
we're not reading out the cmake install directory but have it hardcoded as cmake. That means the ALPSCore files are not found as defaults under macports

**Comment by egull** [comment]
This is where the cmake directory is hardcoded:
ALPSCommonModuleDefinitions.cmake


    132 macro(gen_find_module project_search_file_)
    133   set(PROJECT_SEARCH_FILE ${project_search_file_})
    134   configure_file("${PROJECT_SOURCE_DIR}/../common/cmake/FindALPSModule.cmake.in" "${PROJECT_BINARY_DIR}/Find${PROJECT        _NAME}.cmake" @ONLY)
    135   install(FILES "${PROJECT_BINARY_DIR}/Find${PROJECT_NAME}.cmake" DESTINATION "share/cmake/Modules")
    136   install(FILES "${PROJECT_SOURCE_DIR}/../common/cmake/FindALPSCore.cmake" DESTINATION "share/cmake/Modules")
    137 endmacro(gen_find_module)

**Comment by galexv** [comment]
The variable we should use is `${CMAKE_ROOT}`. From documentation:

     CMAKE_ROOT
          Install directory for running cmake.
   
          This is the install root for the running CMake and the Modules
          directory can be found here.  This is commonly used in this format:
          ${CMAKE_ROOT}/Modules

**Comment by galexv** [comment]
...and the Jenkins builds failed. Apparently, that CMake is old --- will look into it...

**Comment by galexv** [comment]
I worked around this particular error and the project now compiles.

However, it now reports some other errors (which might be harmless in the end). The discussion of the issue behind the errors: http://public.kitware.com/Bug/view.php?id=12588 (the "multiple dependent exported targets").

In our case, i think, it boils down to the fact that we are supporting both "one large build" and "component-by-component build" of ALPSCore: the command `install(EXPORT ...)` works as expected in one case and does not in another. Rather than working around the issue, we can require CMake 2.8.10 that supports the multiple dependent exported targets.

**Comment by galexv** [comment]
CMake 2.8.10 still did not work, 2.8.12 seems to be the minimum required.
Moreover, the builds with 2.8.12 failed (fixed by commits 227dd396, 13ea8e59) while 2.8.12.2 did not have any problems! Maybe we should just bump it to 3.x...
Anyway, it seems working now &mdash; closing the issue.
