### ISSUE TITLE
Is it really needed to fetch GTest via SVN?

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#123]
Asking to have subversion as installation prerequisite while all it does is fetching GTest looks a bit excessive. We can try to find it locally or fetch the source from a fixed URL.

**Comment by aeantipov** [comment]
I'd say - put it in the repo as a "foreign" part. There is also an opportunity to provide GTEST_ROOT and skip the download. And also - without testing, gtest is not downloaded, so the dependency is optional.

**Comment by aeantipov** [comment]
How about putting it under common/gtest?

**Comment by galexv** [comment]
I think it is good. 
After Gabriele tried, following the instructions, to install ALPSCore on a freshly-installed Ubuntu, i am now trying to minimize and document all software dependencies for a default installation. And, i think, it is good to have tests ON by default...

**Comment by egull** [comment]
Yes. I like having the tests on by default. I think we could put google test in a version we like into the source (as a release .tar.gz). The license allows that. It will also mean that we always have a version of google test that we trust (imagine if 5 years down the road someone changes the API... that would break all previous releases?)

Here is the license:

Copyright 2008, Google Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
* Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by aeantipov** [comment]
Fixed in 74441c133fe2a561b60967d3818baacb1cfd1346
