### ISSUE TITLE
jenkins finds problems in hdf5_misc and gtest_par_xml_output

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#134]
The jenkins test with the sanitizer shows two failing tests:

      Start  2: gtest_par_xml_output
 2/40 Test  #2: gtest_par_xml_output .............***Failed    0.75 sec
      Start  9: hdf5_misc
 9/40 Test  #9: hdf5_misc ........................***Failed    0.34 sec

**Comment by galexv** [comment]
That `gtest_par_xml_output()` leaks memory is a documented mis-feature :( See [`alps::gtest_par_xml_output()`](https://alpscore.ci.cloudbees.com/job/alpscore_fedora17_doc-only/ALPSCore_reference/namespacealps.html#ad35f310ffd4d6f10e9953582a6dca822) and [the function definition](https://github.com/ALPSCore/ALPSCore/blob/master/utilities/src/gtest_par_xml_output.cpp#L39).
It should not be a big problem: the function is called only once and only in MPI-parallel tests, and leaks memory only if XML output is requested.

**Comment by egull** [comment]
I looked at this code. I think it's buggy here but I'm not 100% sure what it's supposed to do:

argv[i]=new char[option_prefix_len+arg_new.size()+1]; // NOTE: this memory will never be deallocated :(
memcpy(argv[i], option_prefix, option_prefix_len);
memcpy(argv[i]+option_prefix_len, arg_new.c_str(), arg_new.size()+1);

should it take the content of string argv[i], add to it the contents of string arg_new, and overwrite the pointer to argv[i] with the newly generated string?

If so, would something along the lines of

new_argv+=arg_new;
argv[i]=new char[new_argv.length()];
strcpy(argv[i], new_argv.c_str());

...do the trick? We should go over what the code should do and I can suggest something...

**Comment by aeantipov** [comment]
Should we submit it back to gtest? I understand unlike gtest we have a boost dependence, so it might not be straightforward

**Comment by galexv** [comment]
Here we are just tweaking `argv[]` before gtest has a chance to see it; it is really rather a hack than a solution: we first have to make sure that arguments look like those of gtest; and because we change argv[], we have to allocate memory somewhere, and then deallocate it somehow... all that mess. 

Actually, we can now as well change gtest code itself (as we provide our own version) --- it may be actually simpler, and can be done without any boost dependence! --- and _then_ submit it to gtest.

**Comment by egull** [comment]
...need a faster llvm/clang, not the trunk but one of the current releases.
