### ISSUE TITLE
LogBinning observable doesn't has vector of size 0

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#171]
see the attached code snippet.
#include "alps/accumulators.hpp"
#include "alps/mc/api.hpp"
#include "alps/mc/mcbase.hpp"
#include "alps/mc/parseargs.hpp"
#include "alps/mc/mpiadapter.hpp"
#include "alps/mc/stop_callback.hpp"

typedef alps::accumulators::LogBinningAccumulator<std::vector<double> > vec_obs_t;

class sim: public alps::mcbase{
  public:
  sim(const alps::params & params, std::size_t seed_offset = 42):mcbase(params,seed_offset){
    measurements<<vec_obs_t("vo");
  }

  void update(){}
  double fraction_completed(){ return 1.;}
  void measure(){
    std::vector<double> v1(2,1.);
    std::vector<double> v2(2,2.);
    std::vector<double> v3(2,7.);

    measurements["vo"]<<v1<<v1<<v2<<v2<<v3<<v1;
  }
};

int main(int argc, char **argv){
  boost::mpi::environment env(argc, argv);
  boost::mpi::communicator comm;
  alps::params p; p["Tmin"]=2; p["Tmax"]=10; p["SEED"]=2;
  alps::mcmpiadapter<sim> s(p, comm);
  if(comm.rank()==0) std::cout << "Running simulation..." << std::endl;
  s.run(alps::stop_callback(2));

  // Collect the results from the simulation
  if(comm.rank()==0) std::cout << "Collecting results..." << std::endl;
  alps::results_type<sim>::type results = alps::collect_results(s);

  //check the errors
  std::vector<double> mean=results["vo"].mean<std::vector<double> >();
  std::vector<double> error=results["vo"].error<std::vector<double> >();

  std::cout<<"mean size is: "<<mean.size()<<" error size is: "<<error.size()<<std::endl;
}

**Comment by galexv** [comment]
Can be traced to the fact that `LogBinningAccumulator` does not produce correct results if there are too few data points (1000 is Ok, 100 is too few). Looking at the accumulator --> result conversion for `binning_analysis` accumulator feature...

**Comment by galexv** [comment]
...and this is because when there is not enough bins to know the error, the code returns `alps::inf<T>()` converted to `T`, which is supposed to mean "infinity".  Unfortunately, when `T` is `std::vector<X>`, it has no way to know the length of the vector and returns an empty vector. 

Should not be hard to fix, though. E.g., let's require that the "infinity" constructor should be  `inf<T>(const T& x)`, so that the infinity value may have the same "dimensions" (whatever this means for `T`) as `x`.
