### ISSUE TITLE
Complex number is params

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#188]
Related to #187. 
Should we have complex number in params?

**Comment by egull** [comment]
Can you give an example where you need it?

**Comment by egull** [comment]
Will be dealt with in #195

**Comment by galexv** [comment]
It seems like the request is to have "dictionary object" with complex numbers (issue #188) rather than input of complex numbers in command-line arguments. 
For command-line (or file) arguments the obvious workaround is to provide imaginary and real parts separately (or maybe as an array). 

Closing this issue for now, if anyone feels strongly about it, welcome to reopen. :)
