### ISSUE TITLE
mutable keyword for random number generator

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#204]
Is there a reason to have 

     58             alps::random01 mutable random;

mutable? (in mcbase.hpp). Does it make sense to have the mcbase const and run a calculation, when the measurements are not mutable?

**Comment by galexv** [comment]
I suspect it was rather "show an intent" approach: modifying the RNG state does not change the visible state of `alps::mcbase`. One can also argue that it is `operator()` of the `random01` class that should be declared `const`, because generating a random number does not change the "visible state" of  the RNG, that is, i can get a next random number form a `const` RNG object. 

Anyway, i do not see a particular reason to have it `mutable` --- we can remove the attribute and see if it breaks anything.

**Comment by egull** [comment]
OK. I'll do that locally and see what breaks – and if there's nothing I'll push it. Not sure I agree that one should be able to get a random number from a const rng: while the distribution (uniform_01) remains constant, the engine gets updated (boost::mt19937).

**Comment by egull** [comment]
Changed. Seems to have worked.
