### ISSUE TITLE
Make GTest available for linking by user apps

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#215]
...to avoid code duplication. We can also keep it more or less current, and also we may want to patch it a little to enable testing of MPI programs (right now it is done via a hack).

**Comment by egull** [comment]
I decided against this. There is no clean way to do this, not in the least because the licenses are different. If we did it we would have to install / provide someone else's code, and I don't want to do this. To avoid using multiple gtest one can always specify the gtest location. That way neither ALPS nor a dependent code will download it.

**Comment by egull** [comment]
Closing,. If someone has a clean and practicable solution we will reopen.
