### ISSUE TITLE
Don't throw, just have count=0 on unmeasured observables

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#260]
Follow up on issue #258.
It would be nice if instead of throwing, the code simply considers the observables not measured on some ranks as "measured 0 times" when collecting the results.

**Comment by shinaoka** [comment]
It makes sense.
The collective_merge stuff is implemented below the include/alps/accumulators/feature?

**Comment by mwallerb** [comment]
Quick question: is that such a smart idea? Isn't zero measurements on a subset of cores an indication that something is going severely south?

My reasoning for this goes as follows: say, we do a simple QMC simulation.  Computational complexity is pretty much perfectly correlated with expansion order.  If we impose a fixed time constraint, then the number of measurements *N* will be inversely correlated with the mean expansion order on each core.  Thus a fixed time constraint will introduce a bias towards lower expansion order.  Of course, estimator theory tells us we don't need to worry about this for *N* large, but if *N* is around **zero**, it is IMHO a hail mary of epic proportion to consider the aggregate meaningful in any way.

**Comment by shinaoka** [comment]
Markus, you're right.

For instance, in my worm code, if the simulation time is too short, we fail to visit all subspaces of the enraged configuration space.
This could happen very rarely, but the user should be warned explicitly.

**Comment by jgreitemann** [comment]
One typical scenario where I usually run into this being a problem is when checkpointing a simulation that is still in its thermalization stage. I tend to write checkpoints to disk rather often, so this does happen.

I find it useful to save the simulation periodically, so if it suffers a rare crash I can debug it while only having to rerun the bit since the last checkpoint with the debugger attached. Another case would be if runtime (memory) limits are exceeded and the job is killed by the scheduler. Then, it's nice and easy to request more memory and continue from the most recent checkpoint.

In these cases, not writing the checkpoint and throwing is just about the last thing I want to happen. I agree that bias is a problem in principle when sample sizes are small but (i) this is not a problem that is exclusive to *N=0* but any small *N*, and (ii) it's something that can be decided a posteriori when reviewing the results. Possibly, one could mark the measurement as invalid, e.g. by assigning it an "infinite" error, rather than throwing.
