### ISSUE TITLE
Support for std::complex numbers in accumulators

### ISSUE THREAD

**Issue by jgreitemann** [ALPSCore/ALPSCore#302]
Are there any plans to add support for complex numbers to accumulators? Right now, just adding them to the `ALPS_ACCUMULATORS_USER_TYPES` macro is not sufficient for a number of reasons:
* `error_type` is derived straight from `mean_type` while for complex numbers, `mean_type` should be complex but `error_type` should be real.
* Complex conjugation is missing in the appropriate places. Expressions such as `mean * mean` should be replaced by something akin to `std::norm(mean)`, etc.
* The `vector_functions.hpp` header is insufficient: operators are implemented through `boost::numeric::operators` which doesn't know how to deal with complex numbers and the special functions (trigonometric, sqrt, pow, etc.) templates don't work because they assume their respective scalar counterparts take arguments by value whilst those defined by `<complex>` actually take them by const ref.

Obviously I've given this some thought ;) and tried to implement the missing functionality in a bunch of headers that I could use on top of standard ALPSCore. However, two roadblocks popped up in the process:
* non-member functions cannot be specialized partially which means that I have to specialize fully and use macros to get overrides for `std::complex<float>`, `std::complex<double>`, `std::complex<long double>`;
* I would have to replace the `error` feature with some `cmplx_error` that does the conjugation where necessary. This is rather ugly since I'd have to redefine all the named accumulators. To kill it off completely, the `base_wrapper` does not allow for feature tags other than those hardcoded.

Thus, I'm led to believe the current accumulators cannot just be augmented with some headers to achieve proper handling of complex numbers. The "right" way to do this is to use the `is_complex` type trait to discriminate. I'm going to develop this stuff in my fork of the repo. The main reason I'm writing this is to ask if you guys would be interested in a pull request once it works in which case I would add tests up to your standard. Also, wanting to check in if this has been discussed in your group before and if there are any obstacles I should be aware of.

Thanks for taking the time.

**Comment by galexv** [comment]
Jonas, this subject does come up from time to time, and in my understanding , there are conceptual difficulties with defining an "error bar" in the complex plane: e.g., it's an ellipse rather than a circle (or an interval). I will let Emanuel (@egull) elaborate on this. :)

**Comment by egull** [comment]
Hi Jonas and Alex,
yes, it's really not that easy to say what you mean by an 'error bar' for a complex number. It is easy if you assume that the real and imaginary parts are independent - but there's no reason why that would be a good assumption in general. If they are not, you're being mislead by the 'error bar' as you'd have to measure a covariance matrix.
The problem comes up every now and then and we don't know how to make this general and useful without assuming independence, which (last time around) we decided was too dangerous.

**Comment by mwallerb** [comment]
This is a point of disagreement between Emanuel and me, the root of it is what I see as a conflation of the standard error of the mean with the confidence interval.

In this sense, the same "problem" is present in the real case as well, if the p.d.f. `p = f(x)` is anti-symmetric around the expectation value (think Poisson distribution for low mu, but also the Green's function measurement in tau since it is related to binning):  The standard error of the mean is found from the sample variance. If we take that as an estimate for our error-bar, it is symmetric.  However, arguably a more sensible strategy is to take the inverse of the c.d.f. `x = F^{-1}(P)`, evaluated one sigma on each side of the mean.  This yields the one-sigma confidence interval, which will usually be *anti-symmetric*.

Generalising this to the complex case, we find the confidence intervals as isopleths in the complex plane.  By measuring errors of the real and imaginary part separately, we performed an essentially arbitrary split in the complex plane (think about multiplying your estimate by `exp(i*phi)`) and symmetrised the confidence isopleths along these lines.  This yields arbitrary under- or overestimation of the errorbars, depending on the choice of phase.  The proper way to estimate the confidence interval would be to measure the isopleths directly, e.g., using some spherical multipole expansion, which requires significant effort.

On the other hand, the standard error of the mean is readily generalised to the complex plane. Analogous to the real case, it yields a "circular" error surface (a constant distance from the mean).  I think this is a well-defined and sensible strategy for the error.

**Comment by mwallerb** [comment]
*Minutes of discussion with Emanuel:*
The problem with my definition is a pragmatic one: assume, e.g., that the real part of the estimator is zero by symmetry.  If people then plot the imaginary part with the standard error of the mean directly, they will find that the error bars are "too small" in the sense that not 2/3 of the values have overlap with the result.

So the best way forward would be either (1) to not give errorbars in this case at all or (2) do a "worst-case" estimate by measuring the sample covariance matrix, diagonalising it, and give the largest eigenvalue as error.

**Comment by jgreitemann** [comment]
You are right of course; I sought to generalize to the complex case a little too haphazardly. In the case of isotropic noise, the real variance <|z - < z >|^2> in fact equals the sum of the variances of real and imaginary part, even in the case where those are strong correlated (correlation terms cancel).

By virtue of the central limit theorem, the mean of multi-dimensional independently identical random variables will be distributed according to a Gaussian distribution with the same *covariance matrix* as the individual samples (up to a factor of sqrt(N)). That is, there *is* a qualitative difference from the one-dimensional (real) case: yes, any skewness of the distribution is symmetrized, but the isopleths do *not* become circular; they'll approach ellipses and their eccentricity won't change as more samples are added.

Thus, I believe only the full covariance matrix can provide enough information to interpret the overlap of data in the sense of confidence intervals. This is an issue that is in no way exclusive to complex numbers but would apply to any vector observables in much the same way. The difference for complex numbers only comes into play when propagating the error according to (non-linear) functions.

There can be an argument made here that ALPSCore should provide specialized accumulators which sample the covariance matrix automatically, i.e. add a `covariance_matrix` 'feature'? On the other hand, users can simply sample the correlations themselves should they need them. Having the covariance matrix built-in would however enable correct error propagation. Correct me if I'm wrong, but right now error propagation is only possible for functions of a single observable. Functions of complex numbers however inevitably mix real and imaginary parts and thus the covariance has to be taken into account when propagating the error. Plainly using the scalar variance (i.e. the trace of the covariance matrix) would give wrong results upon error propagation, so I agree with Emanuel that this is not the way to go.

A general treatment of covariance for vector observables would be a huge effort to implement. I think most users would rely on sampling the derived quantities directly rather than propagating the error. For complex-valued observables, though, I think sampling the single off-diagonal covariance doesn't add too much work. We could use type traits to give access to the real and imaginary variance, as well as the cross-correlation.

**Comment by egull** [comment]
That's a good idea – an easy-to-handle complex observable that takes care of correlations between the real and imaginary part in a transparent. Definitely worth thinking about more. I think we should do this as a future feature.
As for the full covariance matrix: this is implemented, but the only code that uses it afaik is the Maxent code, and I don't think it's actively being used by anyone at the moment.

**Comment by egull** [comment]
depends on #37

**Comment by mwallerb** [comment]
Fixed in the ALEA library (commit 5bfd7b61) by using `alps::alea::circular_var` or `alps::alea::elliptic_var`
