### ISSUE TITLE
test mpi_utils_reduce fails

### ISSUE THREAD

**Issue by pbakalov** [ALPSCore/ALPSCore#335]
I'm trying to compile on Ubuntu 12 (Boost 1.61, Cmake 2.8.12).

Upon `make -j10 test` I get:

`       Start  13: mpi_utils_reduce`
` 13/102 Test  #13: mpi_utils_reduce .........................***Failed    0.04 sec
`

All other tests pass. Where could the problem be?

PS during the cmake configuration I get the following (might be relevant):

`-- Compiler does not support MPI. Trying to find MPI`
`-- MPI : Found compiler /usr/bin/mpicxx
`

**Comment by egull** [comment]
Please run the test manually (rather than via make test) and post it's
output here.

**Comment by pbakalov** [comment]
Here it is:
`$ ./utilities/test/mpi_utils_reduce`
`[==========] Running 140 tests from 28 test cases.`
`[----------] Global test environment set-up.`
`[----------] 5 tests from MyPlus/MpiReduceScalarTest/0, where TypeParam = Proxy<char, std::plus>`
`[ RUN      ] MyPlus/MpiReduceScalarTest/0.allreduceByPointer`
`[VirUbuntu12:2966] *** An error occurred in MPI_Allreduce: the reduction operation MPI_SUM is not defined on the MPI_CHAR datatype`
`[VirUbuntu12:2966] *** on communicator MPI_COMM_WORLD`
`[VirUbuntu12:2966] *** MPI_ERR_OP: invalid reduce operation`
`[VirUbuntu12:2966] *** MPI_ERRORS_ARE_FATAL (your MPI job will now abort)`

**Comment by galexv** [comment]
This error seems to be harmless. I will probably be able to fix it (simply
do not test mpi_reduce on type char) once I have a proper connection (I am
out on vacation now). Meantime, I believe it can be safely ignored.

With best regards,
 Alexander.



On Jun 30, 2017 3:24 PM, "pbakalov" <notifications@github.com> wrote:

Here it is:
$ ./utilities/test/mpi_utils_reduce
[==========] Running 140 tests from 28 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from MyPlus/MpiReduceScalarTest/0, where TypeParam =
Proxy<char, std::plus>
[ RUN ] MyPlus/MpiReduceScalarTest/0.allreduceByPointer
[VirUbuntu12:2966] *** An error occurred in MPI_Allreduce: the reduction
operation MPI_SUM is not defined on the MPI_CHAR datatype
[VirUbuntu12:2966] *** on communicator MPI_COMM_WORLD
[VirUbuntu12:2966] *** MPI_ERR_OP: invalid reduce operation
[VirUbuntu12:2966] *** MPI_ERRORS_ARE_FATAL (your MPI job will now abort)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ALPSCore/ALPSCore/issues/335#issuecomment-312226755>,
or mute the thread

**Comment by pbakalov** [comment]
Good to know! Many thanks!

**Comment by galexv** [comment]
@pbakalov I am unable to reproduce the error on systems available here (we don't have Ubuntu 12). Could you please tell the version of MPI you were using?  You can get it by running `mpiexec --version`. Thanks!

**Comment by egull** [comment]
@pbakalov Can you give more information on this? Do things work for you now? We can't reproduce them here.
