### ISSUE TITLE
sum_mpi test  (from MC) fails on Cray (NERSC cori)

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#348]
It is statically compiled ALPSCore with the default cray-HDF5 (1.10.1). The error is:
```
$ srun -n 1 ./mc/test/sum_mpi 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from mc
[ RUN      ] mc.sum_mpi
1+x: Mean +/-error (tau): 1.50019 +/-0.000220675(-0.0807742)
1+x: Mean +/-error (tau): [1.50019,..3..,1.50019] +/-[0.000220675,..3..,0.000220675]([-0.0807742,..3..,-0.0807742])
unknown file: Failure
C++ exception with description "HDF5 error: -1
    #0 H5F.c line 491 in H5Fcreate(): unable to create file
    #1 H5Fint.c line 1168 in H5F_open(): unable to lock the file or initialize file structure
    #2 H5FD.c line 1821 in H5FD_lock(): driver lock request failed
    #3 H5FDsec2.c line 939 in H5FD_sec2_lock(): unable to flock file, errno = 524, error message = 'Unknown error 524'

In ... ALPSCore/hdf5/src/archive.cpp on 114 in resource
.....
" thrown in the test body.
[  FAILED  ] mc.sum_mpi (2686 ms)
```

**Comment by galexv** [comment]
It might be the same bug as issue #290

**Comment by galexv** [comment]
This is likely the file locking problem, as described in several places, e.g. https://lists.hdfgroup.org/pipermail/hdf-forum_lists.hdfgroup.org/2016-May/009480.html
I am testing if 1.10.1 version fixed it for us...

**Comment by galexv** [comment]
It is actually HDF5 bug, and there is a [workaround published](https://support.hdfgroup.org/ftp/HDF5/current/src/unpacked/release_docs/RELEASE.txt) by the HDF5 group. You need to use the updated HDF5 1.10.1; on Cori:
```sh
$ module rm darshan
$ module add hdf5-parallel/1.10.1
```
and then set environment variable:
```sh
$ export HDF5_USE_FILE_LOCKING=FALSE
```
Then the test passes.

Closing this issue now; although this behavior should be documented.

**Comment by DalInar** [comment]
Hi all,

The issue with HDF5 locking is popping up when I try to run DMFT on the Cori compute nodes in the `project` filesystem.   I get the same HDF5 error as above when DMFT tries to write the `cluster.h5` file:
```
C++ exception with description "HDF5 error: -1
    #0 H5F.c line 491 in H5Fcreate(): unable to create file
    #1 H5Fint.c line 1168 in H5F_open(): unable to lock the file or initialize file structure
    #2 H5FD.c line 1821 in H5FD_lock(): driver lock request failed
    #3 H5FDsec2.c line 939 in H5FD_sec2_lock(): unable to flock file, errno = 524, error message = 'Unknown error 524'
```
 I've compiled the code according to [these instructions](https://github.com/egull/CTAUX/wiki/Installing-on-Cori).  The compilation succeeds, and the code can run on a login node, but when I test it with an interactive job on a compute node the code crashes with the HDF5 lock error.  This seems to happen even when I set the `$HDF5_USE_FILE_LOCKING` flag, as suggested by the [Cori docs](http://www.nersc.gov/users/data-analytics/data-management/i-o-libraries/hdf5-2/hdf5/). 

The current work around is just to run the code on the `$SCRATCH` filesystem, where it runs just fine, maybe because they have not turned file locking off on there.

Since it seems we can get around this issue by running on the scratch filesystem, this might not be a critical issue right now.  But I wanted to document that this problem still seems to occur when you try to run DMFT on Cori, and that the proposed solution doesn't seem to fix it.
