### ISSUE TITLE
[accumulators] accumulator_set is not thread-safe

### ISSUE THREAD

**Issue by krivenko** [ALPSCore/ALPSCore#372]
Here is my word of warning to everyone who is going to use the accumulators (present implementation) in a multi-threaded environment.

For purposes of serialization, `alps::accumulators::accumulator_set` keeps a run time registry of all accumulators supported by the library.
https://github.com/ALPSCore/ALPSCore/blob/84bb116d66541cb61543d539b345a1c2f57f367d/accumulators/include/alps/accumulators/wrapper_set.hpp#L166

This registry is a static data member of some auxiliary class. Therefore, it is unsafe to work with in a multi-threaded program. Together with Joe @kleinhenz, we found that constructors of `accumulator_set` will call 
https://github.com/ALPSCore/ALPSCore/blob/84bb116d66541cb61543d539b345a1c2f57f367d/accumulators/include/alps/accumulators/wrapper_set.hpp#L128-L134
without synchronization, and intermittently corrupt memory.

As for a possible resolution of this issue, I suggest adding a warning to the docs. Changing the architecture of `accumulator_set` is probably not worth it, because accumulators are going to be replaced anyway.

**Comment by krivenko** [comment]
Updated Wiki:

https://github.com/ALPSCore/ALPSCore/wiki/Overview/_compare/69f0a4eed412440c99f78dfce7db88751740372e...fd552c2dac09c8f3e7f16a5d6775a54dc6d76676

**Comment by jgreitemann** [comment]
I encountered this problem a while back. Since the race condition occurs in the constructor, the naive workaround of just putting a `critical` in front of the ctor
```cpp
    #pragma omp critical
    sim_type sim(local_params);
```
doesn't work because `critical` will wrap the last line in a nested scope, rendering `sim` inaccessible thereafter. Since simulation classes are most likely not default-constructible, separating the declaration of the variable binding from the actual constructor invocation necessitates the use of a pointer. AFAIK, the safest way to make the construction threadsafe while avoiding default- or copy-construction would be using a throw-away lambda in conjunction with a smart pointer:
```cpp
    sim_type sim = [&] {
        std::unique_ptr<sim_type> sim;
    #pragma omp critical
        sim = std::make_unique<sim_type>(local_params);
        return std::move(*sim);
    } ();
```

**Comment by krivenko** [comment]
Well, I would not be able to use OpenMP workarounds since we rely on a different multi-threading library (HPX).
The actual question is why that registry has to be a non-const static (essentially global) variable.

@galexv @egull Now that I updated the wiki, can we close this issue?

**Comment by egull** [comment]
I'm ok with closing. Alex?

**Comment by galexv** [comment]
I am ok with closing it.
However, as there are users of ALPSCore in multithreaded environment, we should go through the code and make sure it's thread-safe.

**Comment by galexv** [comment]
I'd suggest moving the warning from the Overbview Wiki page (is it really Overview?) to the Known Problems page. I made the Known Problems visible in sidebar.

**Comment by galexv** [comment]
@krivenko @jgreitemann Could you please check if the fix works for you?

**Comment by jgreitemann** [comment]
Yes, this fixes it and renders the workaround I mentioned above superfluous.

**Comment by krivenko** [comment]
@galexv Thank you for the fix, Alex!

I cannot neither confirm nor refute its correctness, because this issue made us stop using `accumulator_set` back in November. Moreover, we plan to switch to ALEA in the next few days...

Even though this is no longer relevant to our work, would you expect `std::mutex` to play along with a different multi-threading library, such as HPX?

**Comment by galexv** [comment]
I am aware that we are changing to Alea anyway, that's why i tried to get away with minimal changes. 

> Even though this is no longer relevant to our work, would you expect std::mutex to play along with a different multi-threading library, such as HPX?

After looking here and there, including Compiler Explorer: C++ mutex is apparently [`pthread_mutex_t`](https://linux.die.net/man/3/pthread_mutex_init) under x86_64 Linux, and should work with any multithreading library based on pthreads. E.g., OpenMP is apparently implemented via pthreads (by gcc on x86_64 Linux). As far as i can guess from my cursory look through HPX sources, it does use POSIX threads under the hood (on Linux).

**Comment by krivenko** [comment]
We had a brief discussion with Joe @kleinhenz and came to a conclusion that pthread locking should be compatible with HPX scheduling mechanism.
