### ISSUE TITLE
boost::program_options for params

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#41]
It would be nice in future to have an interface for alps::params to populate it with the values from command line.

**Comment by galexv** [comment]
I am thinking of pushing the current version of the modified parameter code to a separate branch for "archiving/documentation purposes" --- is it ok? To be merged into the master branch in a few days. Right now some more work is needed on HDF5 save/restore and MPI broadcasting, other major features (including reading lists) seem to function properly.

**Comment by egull** [comment]
ok, sure! Let's do that.

**Comment by galexv** [comment]
Design question:
Currently, it is possible to assign parameters, like this:

    alps::params p;
    p["int_param"]=int(1234);
    int x=p["int_param"];
    assert(x == 1234);

I feel that the interaction of this feature with parameters that are read from a file may be confusing, and would require extensive specification (e.g., "what if i define parameter, as in `p.define<double>("my_par", "My parameter");` which is already assigned as `p["my_par"]=int(1234)` ?"). I suggest prohibiting assigning to undefined parameters:

    alps::params p;
    // ERROR: p["int_param"]=int(1234);
    p.define<int>("int_param", "An integer parameter");
    p["int_param"]=int(1234);
    int x=p["int_param"];
    assert(x == 1234);

OK?

**Comment by aeantipov** [comment]
Mm, this is a little bit of duplicating
<pre>p.define<int>("int_param", "An integer parameter");
p["int_param"]=int(1234);</pre>
This should be probably fine 
<pre>p.define<int>("int_param", "An integer parameter");
p["int_param"]=1234;</pre>

**Comment by galexv** [comment]
Two corrections:

1. It should be `assert(p["int_param"].as<int>()==1234`

2. Yes, of course `int(1234)` is unnecessary (I wrote it for clarity), just `1234` is fine.

**Comment by aeantipov** [comment]
Actually, why that `p["int_param"].as<int>()`? 
Internally, int_param is an int, so probably `p["int_param"]` should just return int. If other type is needed - that probably should go through casting.

**Comment by galexv** [comment]
Short answer --- because boost::program_options keeps parameters as `boost::any` and provides method `as<T>()` to access the underlying value (and the whole thing is designed on top of boost::program_options). Also, it will arguably enforce some discipline on the users, to think what parameter type they are working with (and get an exception if the type is incorrect).

**Comment by aeantipov** [comment]
Hm, so suppose in he code there is an int_param, that was initialized as `p.define<int>("int_param", "An integer parameter");`. This already stores the internal datatype, a.k.a. there should be probably smth like `typedef parameter_type T`, where T is passed to `define<T>`. So basically at this moment the underlying datatype gets stored. Calling once again `as<T2>` when T2 != T looks like a code duplication and probably should not be allowed.

**Comment by jgukelberger** [comment]
Hi guys,

sorry to jump into this without knowing what you already discussed in person, so feel free to ignore me. But I didn't get the need to require so much apparent overhead from the user?

	alps::params p;
	p.define<int>("int_param", "An integer parameter");
	p["int_param"]=1234;
	// ...
	int i = p["int_param"].as<int>();

This to me seems quite awkward for just setting and reading a parameter. What's the problem with allowing 

	alps::params p;
	p["int_param"]=1234;
	// ...
	int i = p["int_param"];

?
If I set a parameter that doesn't exist yet to an int value, why not happily create an int param?
And if I try to read an int, why should I need to write int twice in the same line?

Cheers from Zurich,
Jan

**Comment by galexv** [comment]
I think, my problem is with the code similar to this:

    int argc=2;
    const char* argv[]={"", "--param=1234"}; // emulated command line
    alps::params p(argc,argv);  // associates parameters object with a cmd line and/or parameter file
    p["param"]=4.125; // creates double param
    p.define<int>("param", "An INT parameter meaning ..."); // what should we do here?
    double x=p["param"]; // do i mean integer parameter cast to double, or i expected double param?

IMHO, the main purpose of parameters is to provide an interface to command line and input file. To exchange named data between functions, something like `std::map<string,double>` (or `std::map<string, boost::any>`) would be sufficient... So, some verbosity, clearly indicating "what is the purpose of a parameter" and "value of what type is it expected to contain", would not hurt.

**Comment by jgukelberger** [comment]
Hi Alex,

from a user perspective I'd say you don't care what the exact type in the parameter file or command line is, as long as it can be faithfully converted to/from the variable that I'm reading/writing (why should you?).

Now I do realize that such an interface can be very hard to implement cleanly with boost::any semantics. This was a major reason why we changed to variant for the accumulators.

Cheers,
Jan

**Comment by aeantipov** [comment]
Hm, maybe switch to variant here as well?

**Comment by galexv** [comment]
I think that, if we have a predefined set of supported types, we can do even with `boost::any`, but the types have to be checked at run time. I do not want to get rid of `boost::any` completely, because `boost::program_options` uses `boost::any`, and `boost::program_options` takes care of command line and ini-file parsing. I am thinking it may be possible to use `variant` together with `boost::any`, but, on the other hand, what is wrong with runtime-only checking? Performance is not a concern here...

**Comment by egull** [comment]
Runtime-only checking is fine. As you say: it's not performance critical... we're talking about parameter files after all.

**Comment by jgukelberger** [comment]
Indeed, performance is no issue, it's just about the decision to support a finite set of types. Once this decision is made it's also possible to implement variant semantics on top of boost::any if there is a good reason to do that.

A variant is just the natural choice when you have a restricted set of types and can choose your implementation freely.

**Comment by egull** [comment]
Yes.

Alex figured something out that will allow you to use the syntax you’re used to, at the cost of a bit of coding overhead. More to follow.

**Comment by galexv** [comment]
Let me do another bit of "requirement engineering activity". :)  Suppose, we have the code:

    const char* argv[]={ "", "--somepar=abc" }; // emulated command line
    int argc=2;
    alps::params p(argc, argv); // associates parameters object with the command line
    p["somepar"]=4.125;  // (**1**) assigning a double value 
    p.define<std::string>("somepar", "A string parameter"); // (**2**) attempt to define a string parameter

What should be the outcome of the code? I consider the following options:

1. Explicit assignment overrides the value given in the command line, but still the assigment is equivalent to defining an option "somepar" of type `double`. As the command line argument cannot be converted to `double`, the program fails at the point (**1**).

2. Explicitly assigned parameters that were not previously `define()`-ed have no connections to the command-line options whatsoever. "--somepar=abc" in the command line is ignored, "somepar" is a parameter of type `double` from now on. However, parameters that are already explicitly assigned cannot be `define()`-ed, and the program fails now at the point (**2**).

After some thought, i would go for Option 2, according to the principle of the least surprise (otherwise a perfectly working program can be broken by giving certain command line options...). 

Would be thankful for comments/opinions. :)

**Comment by jgukelberger** [comment]
> After some thought, i would go for Option 2, according to the principle of the least surprise (otherwise a perfectly working program can be broken by giving certain command line options...).
> 
> Would be thankful for comments/opinions. :)

Seems fine to me.

Jan=

**Comment by galexv** [comment]
There may be bugs and i am open to feature requests, but otherwise the new `alps::parameters` code is merged as of 0.3.0-rc1
