### ISSUE TITLE
Document peculiar behavior of HDF5 1.10.1 on Lustre

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#410]
This is related to issue #348. According to [error reports](https://lists.hdfgroup.org/pipermail/hdf-forum_lists.hdfgroup.org/2016-May/009480.html), HDF5 1.10+ does not work well with certain filesystems, in particular Lustre on NERSC's Cori. For HDF5 1.10.1 there is a [workaround](https://support.hdfgroup.org/ftp/HDF5/current/src/unpacked/release_docs/RELEASE.txt) published by HDF5 group.
This behavior causes one of our tests fail on NERSC Cori; the workaround must be documented.

**Comment by DalInar** [comment]
Hi all,

The issue with HDF5 locking is popping up when I try to run DMFT on the Cori compute nodes in the `project` filesystem.   I get the same HDF5 error as above when DMFT tries to write the `cluster.h5` file:
```
C++ exception with description "HDF5 error: -1
    #0 H5F.c line 491 in H5Fcreate(): unable to create file
    #1 H5Fint.c line 1168 in H5F_open(): unable to lock the file or initialize file structure
    #2 H5FD.c line 1821 in H5FD_lock(): driver lock request failed
    #3 H5FDsec2.c line 939 in H5FD_sec2_lock(): unable to flock file, errno = 524, error message = 'Unknown error 524'
```
 I've compiled the code according to [these instructions](https://github.com/egull/CTAUX/wiki/Installing-on-Cori).  The compilation succeeds, and the code can run on a login node, but when I test it with an interactive job on a compute node the code crashes with the HDF5 lock error.  This seems to happen even when I set the `$HDF5_USE_FILE_LOCKING` flag, as suggested by the [Cori docs](http://www.nersc.gov/users/data-analytics/data-management/i-o-libraries/hdf5-2/hdf5/). 

The current work around is just to run the code on the `$SCRATCH` filesystem, where it runs just fine, maybe because they have not turned file locking off on there.

Since it seems we can get around this issue by running on the scratch filesystem, this might not be a critical issue right now.  But I wanted to document that this problem still seems to occur when you try to run DMFT on Cori, and that the proposed solution doesn't seem to fix it.

**Comment by galexv** [comment]
@DalInar Does running "make test" after DMFT is compiled also fail the same way? For  me it does not:
```sh
$ # i am on a compute node:
$ hostname
nid00073
$ # i am in a project filesystem:
$ pwd
/global/homes/g/galexv/project_dir/ALPSCore-stuff/DMFT/000build
$ # setting the variable and running the test:
$ HDF5_USE_FILE_LOCKING=FALSE make test
Running tests...
Test project /global/homes/g/galexv/project_dir/ALPSCore-stuff/DMFT/000build
    Start 1: cluster_helper_test
1/4 Test #1: cluster_helper_test ..............   Passed    5.96 sec
    Start 2: cluster_transform_test
2/4 Test #2: cluster_transform_test ...........   Passed    0.18 sec
    Start 3: double_cell_transform_test
3/4 Test #3: double_cell_transform_test .......   Passed    0.24 sec
    Start 4: normal_state_transform_test
Could not find executable /global/homes/g/galexv/project_dir/ALPSCore-stuff/DMFT/000build/tests/normal_state_transform_test
4/4 Test #4: normal_state_transform_test ......***Not Run   0.00 sec

75% tests passed, 1 tests failed out of 4

Total Test time (real) =   6.48 sec

The following tests FAILED:
	  4 - normal_state_transform_test (Not Run)
```
As expected, one test (the one which fails to compile) is missing, others do pass.

On the other hand, if i do not set `HDF5_USE_FILE_LOCKING=FALSE`, `make test` indeed fails.

If the tests pass for you too, but a "real" run fails, could you please send me the input and the way you run the code? Thanks!

**Comment by DalInar** [comment]
Hi @galexv !  At this point I'm not sure - the unit tests run successfully, but I've recompiled everything with an earlier version of HDF5 (1.8.16), where I don't there was ever a file locking issue.

Here's how I was testing DMFT though:

1. Start an interactive job (somewhere on the `project` filesystem):
```
$ salloc -N 1 -C haswell -t 00:30:00 -L SCRATCH,project
```
2. Export the HDF5 flag:
```
$ export HDF5_USE_FILE_LOCKING=FALSE
```
3. Then try to run DMFT:
```
$ /global/project/projectdirs/m2393/oryx/ALPSCore_Joe/install/bin/dmft paramfile
```

It's when I try to run DMFT that the HDF5 locking error happened on the `project` filesystem.

**Comment by galexv** [comment]
@DalInar Joe, could you please attach your `paramfile` here? (Or is it some paramfile from the DMFT test suite?)

**Comment by galexv** [comment]
I cannot reproduce the error (`make test` in DMFT passes without setting any environment). Maybe NERSC people have fixed the problem?
I am closing the issue for now, @DalInar if you still experience it, please reopen!
