### ISSUE TITLE
alps::param constructor

### ISSUE THREAD

**Issue by iskakoff** [ALPSCore/ALPSCore#416]
What is the reason to have `const char* const* argv` instead of `char** argv` in constructor

    params(int argc, const char* const* argv, const char* hdf5_path="/parameters")

Because the most usual place to use this constructor is in the main function, and you need to do cast, since the main function signature comes without any `const` modifier.

**Comment by galexv** [comment]
I don't think there is any problem with this. The following code:
```c++
#include <iostream>

struct params {
    params(int argc,
           const char* const* argv,
           const char* hdf5_path="/parameters")
    {
        std::cout << "Called ctor with"
                  << " argc=" << argc
                  << " argv=" << argv
                  << " hdf5_path=" << hdf5_path
                  << std::endl;
    }
};

int main(int argc, char** argv)
{
    params p(argc, argv);
    return 0;
}
```
compiles without any warning (`g++ -Wall -std=c++11 -pedantic -o params_const_ctor.x params_const_ctor.cxx`) and works correctly.

> and you need to do cast, since the main function signature comes without any `const` modifier

Actually you don't. Non-const pointer is cast to const-pointer implicitly.
There is usually some confusion there (addressed by [C++ FAQ](https://isocpp.org/wiki/faq/const-correctness#constptrptr-conversion)), but that's why it's `const char* const* argv` rather than `const char** argv`.
