### ISSUE TITLE
Set up a mac build

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#5]

**Comment by aeantipov** [comment]
Cloudbees mac os machines have homebrew built in. Most of the alpscore dependencies (like boost or mpi) come precompiled (so called bottles - available by now for most of the packages). We could make use of that to install dependencies for our builds, instead of compiling them ourselves. This would probably make them slower, but would solve a problem with, for example, openmpi not being accessible on a filesystem. 

We could also use that to 
1) Create a precompiled alpscore package (see https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md ). 
2) Create some of the precompiled dependencies with special flags.
3) Have more flexibility - check compatibility with different versions of packages by using https://github.com/Homebrew/homebrew-versions

**Comment by egull** [comment]
I'm closing this one but I'll open a new one to explore homebrew on jenkins
