### ISSUE TITLE
[alea] linear_prop is broken for batched accumulators

### ISSUE THREAD

**Issue by kleinhenz** [ALPSCore/ALPSCore#506]
Linear propagation gives incorrect results when the input accumulator is batched, e.g. `batch_acc` or `cov_acc` with `bundle_size > 1`. I think this has to do with `count2` not being computed correctly.

MWE

```
#include <iostream>
#include <random>
#include <vector>
#include <alps/alea.hpp>

int main(int argc, char* argv[]){
  std::random_device rd{};
  std::mt19937 gen {rd()};

  std::normal_distribution<> d {0.0, 2.0};
  alps::alea::batch_acc<double> acc(1);

  int N = 1000000;
  for (int i = 0; i < N; ++i) {
    acc << d(gen);
  }

  auto result = acc.result();

  std::function<double(double)> f = [](double x) { return x; };
  auto tf = alps::alea::make_transformer(f);
  auto transformed_result =
      alps::alea::transform(alps::alea::linear_prop(), tf, result);

  std::cout << result << std::endl;
  std::cout << transformed_result << std::endl;
}
```

Produces output

```
0.00108921 +- 0.00194441
0.00108921 +- 0.123001
```

**Comment by krivenko** [comment]
The problem is here:
https://github.com/ALPSCore/ALPSCore/blob/e70f3a9820e41276e9825f8da080419782f67b93/alea/include/alps/alea/transform.hpp#L62

If `in` is a `cov_result`, `in.cov()` returns `batch_size() * store_->data2()`. I guess one has to rescale the result back before storing it in `res.store().data2()`.

**Comment by egull** [comment]
@mwallerb please make fixing this a priority.
