### ISSUE TITLE
[alea] Fails to compile on 32-bit Linux

### ISSUE THREAD

**Issue by wistaria** [ALPSCore/ALPSCore#581]
autocorr.cpp fails to compile on 32-bit Debian Stretch:

* cat /etc/debian_version -> 9.5
* dpkg --print-architecture -> i386
* gcc --version -> gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

Error log: [error.txt](https://github.com/ALPSCore/ALPSCore/files/2541123/error.txt)

**Comment by egull** [comment]
Markus this is your header – please have a look asap and if you can't find the problem reassign back to me.

**Comment by wistaria** [comment]
Indeed, std::size_t is "unsigned long" in 64-bit architecture, while it is "unsigned int" in 32-bit OS. In order to ensure "binary compatibility" between 32 and 64 architectures, we should cast to/from uint64_t before writing to archive (after reading from archive).

**Comment by mwallerb** [comment]
@wistaria thank you for catching this!  When designing the library, I did not think of 32-bit users, so I took the shortcut `sizeof(size_t) == sizeof(long)`, which fails on 32-bit systems.  

However, rather than casting before writing, I think we need to move to a 64-bit number, because otherwise the counters in the accumulators overflow for more than `2^32 ~ 4e9` measurements, which is not inconceivable.

@wistaria  I propose we move to `uint64_t` where applicable.  To make sure that this actually fixes your bug, can you check that `uint64_t` is available on your system (it might not be since its a 32-bit machine)?
