### ISSUE TITLE
More sensible error message if observable does not exist

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#75]
try measuring for an observable that does not exist. Right now the error is:

Assertion failed: (px != 0), function operator*, file /opt/local/include/boost/smart_ptr/shared_ptr.hpp, line 641.

this should be changed to something more sensible, like 'Error: observable does not exist"

**Comment by galexv** [comment]
Fixed by commit 6dd2ef7.

It is done by checking if the pointer is valid before every dereference inside `accumulator_wrapper` (and hoping that all dereferences are accounted for). As this test is unnecessary in 99% cases, it would be better to initialize the non-existing slots in `accumulator_set` with some dummy object that will throw an exception on access. Can be done some other time...
